### ISSUE TITLE
g_sOSProperties has wrong length, in file usb_serial_structs.h 

### ISSUE THREAD

**Issue by Howerd** [MaciejKucia/OS_Descriptors#1]
Hi Maciej,

Thanks for publishing your project :-)
I noticed that the length of the bPropertyData3 in usb_serial_structs.h field had a length of 37, but the string in usb_serial_structs.c is actually 39 characters long. This could explain why Icons do not work!

Best regards,
Howerd ( howerd@inventio.co.uk )

typedef const struct __attribute__((__packed__)) {
	const uint32_t dwLength;
	const uint16_t bcdVersion;
....
	const uint32_t dwPropertyDataLength3;
	const uint16_t bPropertyData3[39];  // should be [39], not [37] !!!!
} g_sOSProperties;

**Comment by MaciejKucia** [comment]
Thanks! It's now fixed with 4e417f4f44db1ff9a93bc01dc2ffec1c9260988d
I haven't checked the code yet, need to get the hardware first.
